# Taking the 'run_tests_with_npm' sample configuration from https://circleci.com/developer/orbs/orb/circleci/node 

version: '2.1'
orbs:
  node: circleci/node@4.7
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - test

